### ISSUE TITLE
GPS Systems

### ISSUE THREAD

**Issue by ausshir** [UofSSpaceDesignTeam/balloon-software#5]
- Need something that will allow us to go over 20k ft

**Comment by ottopasuuna** [comment]
Here is a site that lists some GPS units for HABS. [https://ukhas.org.uk/guides:gps_modules](https://ukhas.org.uk/guides:gps_modules)
It also links to a Wikepedia article on CoCom that mentions the limitations imposed on GPS

> In GPS technology, the term "COCOM Limits" also refers to a limit placed on GPS tracking devices that disables tracking when the device calculates that it is moving faster than 1,000 knots (1,900 km/h; 1,200 mph) at an altitude higher than 18,000 m (59,000 ft).[2] This was intended to prevent the use of GPS in intercontinental ballistic missile-like applications. Some manufacturers apply this limit only when both speed and altitude limits are reached, while other manufacturers disable tracking when either limit is reached. In the latter case, this causes some devices to refuse to operate in very high altitude balloons.

So if the gps module disables its self only when both conditoins are met, it should still work for a high altitude balloon.

**Comment by bht822** [comment]
http://www.habduino.org/
